AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 190

Metrics/ParameterLists:
  Max: 8

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
